name: Standards Check

on: [pull_request, push]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: ${{ github.event_name == 'pull_request' && 20 || 1 }}

      - uses: deepakputhraya/action-branch-name@v1.0.0
        if: github.event_name == 'pull_request'
        with:
          regex: '^(feature|bugfix)\/.+'

      - uses: gsactions/commit-message-checker@v2
        with:
          pattern: '^.+(\n.*)*\nIssue:\s*#\d+\s*$'
          flags: "gm"
          error: 'Commit must include "Issue: #number"'
          accessToken: ${{ secrets.GITHUB_TOKEN }}
