name: Standards Check

on: [pull_request, push]

jobs:
  check:
    if: github.repository != format('{0}/.github', github.repository_owner)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: deepakputhraya/action-branch-name@v1.0.0
        if: github.event_name == 'pull_request'
        with:
          regex: '^(feature|bugfix)\/.+'

      - uses: taskmedia/action-conventional-commits@v1
        with:
          pattern: '^.+(\n.*)*\nIssue:\s*#\d+\s*$'
