name: Reusable Standards Check
on:
  workflow_call:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: ${{ github.event_name == 'pull_request' && 20 || 1 }}
      - uses: deepakputhraya/action-branch-name@v1.0.0
        if: github.event_name == 'pull_request'
        with:
          regex: '^(feature|bugfix)\/.+'
      - uses: gsactions/commit-message-checker@v2
        with:
          pattern: '^.+(\n.*)*\n\nIssue:\s*#\d+\s*$'
          flags: "gm"
          error: "Commit format is incorrect"
          excludeTitle: true # Исключить заголовок PR
          excludeDescription: true # Исключить описание PR
          accessToken: ${{ secrets.GITHUB_TOKEN }}
